-- MySQL Script generated by MySQL Workbench
-- Sat Sep 25 09:10:48 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bt60wa8k2nl1ejk6irrq
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bt60wa8k2nl1ejk6irrq` ;

-- -----------------------------------------------------
-- Schema bt60wa8k2nl1ejk6irrq
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bt60wa8k2nl1ejk6irrq` DEFAULT CHARACTER SET utf8 ;
USE `bt60wa8k2nl1ejk6irrq` ;

-- -----------------------------------------------------
-- Table `bt60wa8k2nl1ejk6irrq`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bt60wa8k2nl1ejk6irrq`.`tipo_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bt60wa8k2nl1ejk6irrq`.`parentesco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bt60wa8k2nl1ejk6irrq`.`parentesco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `parentesco` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bt60wa8k2nl1ejk6irrq`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bt60wa8k2nl1ejk6irrq`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_id` VARCHAR(45) NOT NULL,
  `nro_documento` INT NOT NULL,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `departamento` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(255) NOT NULL,
  `parentesco_id` INT NOT NULL,
  `tipo_usuario` INT NOT NULL,
  `titular_id` INT NOT NULL,
  `imgUrl` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_tipo_usuario1_idx` (`tipo_usuario` ASC) ,
  INDEX `fk_users_parentesco1_idx` (`parentesco_id` ASC) ,
  INDEX `fk_users_users1_idx` (`titular_id` ASC) ,
  CONSTRAINT `fk_users_tipo_usuario1`
    FOREIGN KEY (`tipo_usuario`)
    REFERENCES `bt60wa8k2nl1ejk6irrq`.`tipo_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_parentesco1`
    FOREIGN KEY (`parentesco_id`)
    REFERENCES `bt60wa8k2nl1ejk6irrq`.`parentesco` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_users_users1`
    FOREIGN KEY (`titular_id`)
    REFERENCES `bt60wa8k2nl1ejk6irrq`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bt60wa8k2nl1ejk6irrq`.`municipios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bt60wa8k2nl1ejk6irrq`.`municipios` (
  `id_municipio` INT NOT NULL,
  `municipio` VARCHAR(45) NOT NULL,
  `estado` INT NOT NULL,
  `departamento_id` INT NOT NULL,
  PRIMARY KEY (`id_municipio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bt60wa8k2nl1ejk6irrq`.`departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bt60wa8k2nl1ejk6irrq`.`departamentos` (
  `id_departamento` INT NOT NULL,
  `departamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_departamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bt60wa8k2nl1ejk6irrq`.`medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bt60wa8k2nl1ejk6irrq`.`medico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `identificacion` INT NOT NULL,
  `especializacion` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `modalidad_cita` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bt60wa8k2nl1ejk6irrq`.`agenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bt60wa8k2nl1ejk6irrq`.`agenda` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `especialidad` VARCHAR(45) NOT NULL,
  `medico_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `fk_agenda_medico1_idx` (`medico_id` ASC) ,
  CONSTRAINT `fk_agenda_medico1`
    FOREIGN KEY (`medico_id`)
    REFERENCES `bt60wa8k2nl1ejk6irrq`.`medico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bt60wa8k2nl1ejk6irrq`.`cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bt60wa8k2nl1ejk6irrq`.`cita` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `agenda_id` INT NOT NULL,
  `beneficiario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cita_agenda1_idx` (`agenda_id` ASC) ,
  INDEX `fk_cita_users1_idx` (`beneficiario_id` ASC) ,
  CONSTRAINT `fk_cita_agenda1`
    FOREIGN KEY (`agenda_id`)
    REFERENCES `bt60wa8k2nl1ejk6irrq`.`agenda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cita_users1`
    FOREIGN KEY (`beneficiario_id`)
    REFERENCES `bt60wa8k2nl1ejk6irrq`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bt60wa8k2nl1ejk6irrq`.`tipo_estudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bt60wa8k2nl1ejk6irrq`.`tipo_estudio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_estudio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bt60wa8k2nl1ejk6irrq`.`estudios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bt60wa8k2nl1ejk6irrq`.`estudios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `fecha_obtencion` DATE NULL,
  `tipo_estudio` INT NOT NULL,
  `medico_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_estudios_tipo_estudio1_idx` (`tipo_estudio` ASC) ,
  INDEX `fk_estudios_medico1_idx` (`medico_id` ASC) ,
  CONSTRAINT `fk_estudios_tipo_estudio1`
    FOREIGN KEY (`tipo_estudio`)
    REFERENCES `bt60wa8k2nl1ejk6irrq`.`tipo_estudio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudios_medico1`
    FOREIGN KEY (`medico_id`)
    REFERENCES `bt60wa8k2nl1ejk6irrq`.`medico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bt60wa8k2nl1ejk6irrq`.`credencial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bt60wa8k2nl1ejk6irrq`.`credencial` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `beneficiario_id` INT NOT NULL,
  `fecha_vencimiento` DATE NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_credencial_users1_idx` (`beneficiario_id` ASC) ,
  CONSTRAINT `fk_credencial_users1`
    FOREIGN KEY (`beneficiario_id`)
    REFERENCES `bt60wa8k2nl1ejk6irrq`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
